name: Build Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks libzip-dev zip
          sudo luarocks install love-release

      - name: Package game
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          love-release -M -W64 -v "$VERSION" -l 11.3 --uti com.stellar.assault

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            releases/stellar-assault.love
            releases/stellar-assault-win64.zip
            releases/stellar-assault-macos.zip
