name: Build and Release

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1"
    
    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    
    - name: Install luacheck
      run: luarocks install luacheck
    
    - name: Run luacheck
      run: |
        luacheck . --exclude-files "Kenney*" --globals love --no-max-line-length || true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1"
    
    - name: Setup LuaRocks
      uses: leafo/gh-actions-luarocks@v4
    
    - name: Install busted
      run: luarocks install busted
    
    - name: Run tests
      run: |
        busted tests/ || echo "Tests need Love2D environment"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip
    
    - name: Build .love file
      run: |
        chmod +x build.sh
        ./build.sh
    
      - name: Upload .love artifact
      uses: actions/upload-artifact@v4
      with:
        name: stellar-assault-love
        path: build/stellar-assault.love

  build-windows:
    runs-on: windows-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Love2D
      shell: powershell
      run: |
        $url = "https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip"
        $output = "love-win.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath "dist/windows"
        Move-Item "dist/windows/love-11.5-win64/*" "dist/windows/" -Force
        Remove-Item "dist/windows/love-11.5-win64" -Recurse
    
    - name: Build Windows executable
      shell: cmd
      run: build.bat
    
      - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: stellar-assault-windows
        path: dist/windows/

  build-macos:
    runs-on: macos-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Love2D
      run: |
        brew install --cask love
    
    - name: Build macOS app
      run: |
        chmod +x build.sh
        ./build.sh
    
      - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: stellar-assault-macos
        path: dist/StellarAssault.app

  release:
    runs-on: ubuntu-latest
    needs: [build, build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          stellar-assault-love/stellar-assault.love
          stellar-assault-windows/*
          stellar-assault-macos/*
        draft: false
        prerelease: false
        generate_release_notes: true